// This file isn't generated, but this comment is necessary to exclude it from StyleCop analysis.
// <auto-generated/>
//Apache2, 2014-2016, Samuel Carlsson

using System.IO;
namespace NOpenType.Tables
{
    static class BoundsReader
    {
        public static Bounds ReadFrom(BinaryReader input)
        { 
            //xmin, ymin,xmax,ymax
            return new Bounds(input.ReadInt16(), input.ReadInt16(), input.ReadInt16(), input.ReadInt16());
        }
    }
}
