// Copyright (c) Six Labors.
// Licensed under the Six Labors Split License.

// <auto-generated />
using SixLabors.ImageSharp.Formats.Bmp;
using SixLabors.ImageSharp.Formats.Cur;
using SixLabors.ImageSharp.Formats.Gif;
using SixLabors.ImageSharp.Formats.Ico;
using SixLabors.ImageSharp.Formats.Jpeg;
using SixLabors.ImageSharp.Formats.Pbm;
using SixLabors.ImageSharp.Formats.Png;
using SixLabors.ImageSharp.Formats.Qoi;
using SixLabors.ImageSharp.Formats.Tga;
using SixLabors.ImageSharp.Formats.Tiff;
using SixLabors.ImageSharp.Formats.Webp;

namespace SixLabors.ImageSharp;

/// <summary>
/// Extension methods for the <see cref="Image"/> type.
/// </summary>
public static partial class ImageExtensions
{
    /// <summary>
    /// Saves the image to the given stream with the Bmp format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    public static void SaveAsBmp(this Image source, string path) => SaveAsBmp(source, path, default);

    /// <summary>
    /// Saves the image to the given stream with the Bmp format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsBmpAsync(this Image source, string path) => SaveAsBmpAsync(source, path, default);

    /// <summary>
    /// Saves the image to the given stream with the Bmp format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsBmpAsync(this Image source, string path, CancellationToken cancellationToken)
        => SaveAsBmpAsync(source, path, default, cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Bmp format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    public static void SaveAsBmp(this Image source, string path, BmpEncoder encoder) =>
        source.Save(
            path,
            encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(BmpFormat.Instance));

    /// <summary>
    /// Saves the image to the given stream with the Bmp format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsBmpAsync(this Image source, string path, BmpEncoder encoder, CancellationToken cancellationToken = default)
        => source.SaveAsync(
              path,
              encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(BmpFormat.Instance),
              cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Bmp format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    public static void SaveAsBmp(this Image source, Stream stream)
        => SaveAsBmp(source, stream, default);

    /// <summary>
    /// Saves the image to the given stream with the Bmp format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsBmpAsync(this Image source, Stream stream, CancellationToken cancellationToken = default)
        => SaveAsBmpAsync(source, stream, default, cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Bmp format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    public static void SaveAsBmp(this Image source, Stream stream, BmpEncoder encoder)
        => source.Save(
              stream,
              encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(BmpFormat.Instance));

    /// <summary>
    /// Saves the image to the given stream with the Bmp format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsBmpAsync(this Image source, Stream stream, BmpEncoder encoder, CancellationToken cancellationToken = default)
        => source.SaveAsync(
              stream,
              encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(BmpFormat.Instance),
              cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Cur format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    public static void SaveAsCur(this Image source, string path) => SaveAsCur(source, path, default);

    /// <summary>
    /// Saves the image to the given stream with the Cur format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsCurAsync(this Image source, string path) => SaveAsCurAsync(source, path, default);

    /// <summary>
    /// Saves the image to the given stream with the Cur format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsCurAsync(this Image source, string path, CancellationToken cancellationToken)
        => SaveAsCurAsync(source, path, default, cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Cur format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    public static void SaveAsCur(this Image source, string path, CurEncoder encoder) =>
        source.Save(
            path,
            encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(CurFormat.Instance));

    /// <summary>
    /// Saves the image to the given stream with the Cur format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsCurAsync(this Image source, string path, CurEncoder encoder, CancellationToken cancellationToken = default)
        => source.SaveAsync(
              path,
              encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(CurFormat.Instance),
              cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Cur format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    public static void SaveAsCur(this Image source, Stream stream)
        => SaveAsCur(source, stream, default);

    /// <summary>
    /// Saves the image to the given stream with the Cur format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsCurAsync(this Image source, Stream stream, CancellationToken cancellationToken = default)
        => SaveAsCurAsync(source, stream, default, cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Cur format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    public static void SaveAsCur(this Image source, Stream stream, CurEncoder encoder)
        => source.Save(
              stream,
              encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(CurFormat.Instance));

    /// <summary>
    /// Saves the image to the given stream with the Cur format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsCurAsync(this Image source, Stream stream, CurEncoder encoder, CancellationToken cancellationToken = default)
        => source.SaveAsync(
              stream,
              encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(CurFormat.Instance),
              cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Gif format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    public static void SaveAsGif(this Image source, string path) => SaveAsGif(source, path, default);

    /// <summary>
    /// Saves the image to the given stream with the Gif format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsGifAsync(this Image source, string path) => SaveAsGifAsync(source, path, default);

    /// <summary>
    /// Saves the image to the given stream with the Gif format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsGifAsync(this Image source, string path, CancellationToken cancellationToken)
        => SaveAsGifAsync(source, path, default, cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Gif format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    public static void SaveAsGif(this Image source, string path, GifEncoder encoder) =>
        source.Save(
            path,
            encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(GifFormat.Instance));

    /// <summary>
    /// Saves the image to the given stream with the Gif format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsGifAsync(this Image source, string path, GifEncoder encoder, CancellationToken cancellationToken = default)
        => source.SaveAsync(
              path,
              encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(GifFormat.Instance),
              cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Gif format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    public static void SaveAsGif(this Image source, Stream stream)
        => SaveAsGif(source, stream, default);

    /// <summary>
    /// Saves the image to the given stream with the Gif format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsGifAsync(this Image source, Stream stream, CancellationToken cancellationToken = default)
        => SaveAsGifAsync(source, stream, default, cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Gif format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    public static void SaveAsGif(this Image source, Stream stream, GifEncoder encoder)
        => source.Save(
              stream,
              encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(GifFormat.Instance));

    /// <summary>
    /// Saves the image to the given stream with the Gif format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsGifAsync(this Image source, Stream stream, GifEncoder encoder, CancellationToken cancellationToken = default)
        => source.SaveAsync(
              stream,
              encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(GifFormat.Instance),
              cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Ico format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    public static void SaveAsIco(this Image source, string path) => SaveAsIco(source, path, default);

    /// <summary>
    /// Saves the image to the given stream with the Ico format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsIcoAsync(this Image source, string path) => SaveAsIcoAsync(source, path, default);

    /// <summary>
    /// Saves the image to the given stream with the Ico format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsIcoAsync(this Image source, string path, CancellationToken cancellationToken)
        => SaveAsIcoAsync(source, path, default, cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Ico format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    public static void SaveAsIco(this Image source, string path, IcoEncoder encoder) =>
        source.Save(
            path,
            encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(IcoFormat.Instance));

    /// <summary>
    /// Saves the image to the given stream with the Ico format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsIcoAsync(this Image source, string path, IcoEncoder encoder, CancellationToken cancellationToken = default)
        => source.SaveAsync(
              path,
              encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(IcoFormat.Instance),
              cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Ico format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    public static void SaveAsIco(this Image source, Stream stream)
        => SaveAsIco(source, stream, default);

    /// <summary>
    /// Saves the image to the given stream with the Ico format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsIcoAsync(this Image source, Stream stream, CancellationToken cancellationToken = default)
        => SaveAsIcoAsync(source, stream, default, cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Ico format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    public static void SaveAsIco(this Image source, Stream stream, IcoEncoder encoder)
        => source.Save(
              stream,
              encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(IcoFormat.Instance));

    /// <summary>
    /// Saves the image to the given stream with the Ico format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsIcoAsync(this Image source, Stream stream, IcoEncoder encoder, CancellationToken cancellationToken = default)
        => source.SaveAsync(
              stream,
              encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(IcoFormat.Instance),
              cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Jpeg format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    public static void SaveAsJpeg(this Image source, string path) => SaveAsJpeg(source, path, default);

    /// <summary>
    /// Saves the image to the given stream with the Jpeg format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsJpegAsync(this Image source, string path) => SaveAsJpegAsync(source, path, default);

    /// <summary>
    /// Saves the image to the given stream with the Jpeg format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsJpegAsync(this Image source, string path, CancellationToken cancellationToken)
        => SaveAsJpegAsync(source, path, default, cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Jpeg format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    public static void SaveAsJpeg(this Image source, string path, JpegEncoder encoder) =>
        source.Save(
            path,
            encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(JpegFormat.Instance));

    /// <summary>
    /// Saves the image to the given stream with the Jpeg format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsJpegAsync(this Image source, string path, JpegEncoder encoder, CancellationToken cancellationToken = default)
        => source.SaveAsync(
              path,
              encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(JpegFormat.Instance),
              cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Jpeg format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    public static void SaveAsJpeg(this Image source, Stream stream)
        => SaveAsJpeg(source, stream, default);

    /// <summary>
    /// Saves the image to the given stream with the Jpeg format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsJpegAsync(this Image source, Stream stream, CancellationToken cancellationToken = default)
        => SaveAsJpegAsync(source, stream, default, cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Jpeg format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    public static void SaveAsJpeg(this Image source, Stream stream, JpegEncoder encoder)
        => source.Save(
              stream,
              encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(JpegFormat.Instance));

    /// <summary>
    /// Saves the image to the given stream with the Jpeg format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsJpegAsync(this Image source, Stream stream, JpegEncoder encoder, CancellationToken cancellationToken = default)
        => source.SaveAsync(
              stream,
              encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(JpegFormat.Instance),
              cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Pbm format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    public static void SaveAsPbm(this Image source, string path) => SaveAsPbm(source, path, default);

    /// <summary>
    /// Saves the image to the given stream with the Pbm format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsPbmAsync(this Image source, string path) => SaveAsPbmAsync(source, path, default);

    /// <summary>
    /// Saves the image to the given stream with the Pbm format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsPbmAsync(this Image source, string path, CancellationToken cancellationToken)
        => SaveAsPbmAsync(source, path, default, cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Pbm format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    public static void SaveAsPbm(this Image source, string path, PbmEncoder encoder) =>
        source.Save(
            path,
            encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(PbmFormat.Instance));

    /// <summary>
    /// Saves the image to the given stream with the Pbm format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsPbmAsync(this Image source, string path, PbmEncoder encoder, CancellationToken cancellationToken = default)
        => source.SaveAsync(
              path,
              encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(PbmFormat.Instance),
              cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Pbm format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    public static void SaveAsPbm(this Image source, Stream stream)
        => SaveAsPbm(source, stream, default);

    /// <summary>
    /// Saves the image to the given stream with the Pbm format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsPbmAsync(this Image source, Stream stream, CancellationToken cancellationToken = default)
        => SaveAsPbmAsync(source, stream, default, cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Pbm format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    public static void SaveAsPbm(this Image source, Stream stream, PbmEncoder encoder)
        => source.Save(
              stream,
              encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(PbmFormat.Instance));

    /// <summary>
    /// Saves the image to the given stream with the Pbm format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsPbmAsync(this Image source, Stream stream, PbmEncoder encoder, CancellationToken cancellationToken = default)
        => source.SaveAsync(
              stream,
              encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(PbmFormat.Instance),
              cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Png format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    public static void SaveAsPng(this Image source, string path) => SaveAsPng(source, path, default);

    /// <summary>
    /// Saves the image to the given stream with the Png format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsPngAsync(this Image source, string path) => SaveAsPngAsync(source, path, default);

    /// <summary>
    /// Saves the image to the given stream with the Png format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsPngAsync(this Image source, string path, CancellationToken cancellationToken)
        => SaveAsPngAsync(source, path, default, cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Png format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    public static void SaveAsPng(this Image source, string path, PngEncoder encoder) =>
        source.Save(
            path,
            encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(PngFormat.Instance));

    /// <summary>
    /// Saves the image to the given stream with the Png format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsPngAsync(this Image source, string path, PngEncoder encoder, CancellationToken cancellationToken = default)
        => source.SaveAsync(
              path,
              encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(PngFormat.Instance),
              cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Png format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    public static void SaveAsPng(this Image source, Stream stream)
        => SaveAsPng(source, stream, default);

    /// <summary>
    /// Saves the image to the given stream with the Png format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsPngAsync(this Image source, Stream stream, CancellationToken cancellationToken = default)
        => SaveAsPngAsync(source, stream, default, cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Png format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    public static void SaveAsPng(this Image source, Stream stream, PngEncoder encoder)
        => source.Save(
              stream,
              encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(PngFormat.Instance));

    /// <summary>
    /// Saves the image to the given stream with the Png format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsPngAsync(this Image source, Stream stream, PngEncoder encoder, CancellationToken cancellationToken = default)
        => source.SaveAsync(
              stream,
              encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(PngFormat.Instance),
              cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Qoi format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    public static void SaveAsQoi(this Image source, string path) => SaveAsQoi(source, path, default);

    /// <summary>
    /// Saves the image to the given stream with the Qoi format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsQoiAsync(this Image source, string path) => SaveAsQoiAsync(source, path, default);

    /// <summary>
    /// Saves the image to the given stream with the Qoi format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsQoiAsync(this Image source, string path, CancellationToken cancellationToken)
        => SaveAsQoiAsync(source, path, default, cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Qoi format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    public static void SaveAsQoi(this Image source, string path, QoiEncoder encoder) =>
        source.Save(
            path,
            encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(QoiFormat.Instance));

    /// <summary>
    /// Saves the image to the given stream with the Qoi format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsQoiAsync(this Image source, string path, QoiEncoder encoder, CancellationToken cancellationToken = default)
        => source.SaveAsync(
              path,
              encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(QoiFormat.Instance),
              cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Qoi format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    public static void SaveAsQoi(this Image source, Stream stream)
        => SaveAsQoi(source, stream, default);

    /// <summary>
    /// Saves the image to the given stream with the Qoi format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsQoiAsync(this Image source, Stream stream, CancellationToken cancellationToken = default)
        => SaveAsQoiAsync(source, stream, default, cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Qoi format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    public static void SaveAsQoi(this Image source, Stream stream, QoiEncoder encoder)
        => source.Save(
              stream,
              encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(QoiFormat.Instance));

    /// <summary>
    /// Saves the image to the given stream with the Qoi format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsQoiAsync(this Image source, Stream stream, QoiEncoder encoder, CancellationToken cancellationToken = default)
        => source.SaveAsync(
              stream,
              encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(QoiFormat.Instance),
              cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Tga format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    public static void SaveAsTga(this Image source, string path) => SaveAsTga(source, path, default);

    /// <summary>
    /// Saves the image to the given stream with the Tga format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsTgaAsync(this Image source, string path) => SaveAsTgaAsync(source, path, default);

    /// <summary>
    /// Saves the image to the given stream with the Tga format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsTgaAsync(this Image source, string path, CancellationToken cancellationToken)
        => SaveAsTgaAsync(source, path, default, cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Tga format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    public static void SaveAsTga(this Image source, string path, TgaEncoder encoder) =>
        source.Save(
            path,
            encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(TgaFormat.Instance));

    /// <summary>
    /// Saves the image to the given stream with the Tga format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsTgaAsync(this Image source, string path, TgaEncoder encoder, CancellationToken cancellationToken = default)
        => source.SaveAsync(
              path,
              encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(TgaFormat.Instance),
              cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Tga format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    public static void SaveAsTga(this Image source, Stream stream)
        => SaveAsTga(source, stream, default);

    /// <summary>
    /// Saves the image to the given stream with the Tga format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsTgaAsync(this Image source, Stream stream, CancellationToken cancellationToken = default)
        => SaveAsTgaAsync(source, stream, default, cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Tga format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    public static void SaveAsTga(this Image source, Stream stream, TgaEncoder encoder)
        => source.Save(
              stream,
              encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(TgaFormat.Instance));

    /// <summary>
    /// Saves the image to the given stream with the Tga format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsTgaAsync(this Image source, Stream stream, TgaEncoder encoder, CancellationToken cancellationToken = default)
        => source.SaveAsync(
              stream,
              encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(TgaFormat.Instance),
              cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Tiff format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    public static void SaveAsTiff(this Image source, string path) => SaveAsTiff(source, path, default);

    /// <summary>
    /// Saves the image to the given stream with the Tiff format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsTiffAsync(this Image source, string path) => SaveAsTiffAsync(source, path, default);

    /// <summary>
    /// Saves the image to the given stream with the Tiff format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsTiffAsync(this Image source, string path, CancellationToken cancellationToken)
        => SaveAsTiffAsync(source, path, default, cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Tiff format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    public static void SaveAsTiff(this Image source, string path, TiffEncoder encoder) =>
        source.Save(
            path,
            encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(TiffFormat.Instance));

    /// <summary>
    /// Saves the image to the given stream with the Tiff format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsTiffAsync(this Image source, string path, TiffEncoder encoder, CancellationToken cancellationToken = default)
        => source.SaveAsync(
              path,
              encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(TiffFormat.Instance),
              cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Tiff format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    public static void SaveAsTiff(this Image source, Stream stream)
        => SaveAsTiff(source, stream, default);

    /// <summary>
    /// Saves the image to the given stream with the Tiff format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsTiffAsync(this Image source, Stream stream, CancellationToken cancellationToken = default)
        => SaveAsTiffAsync(source, stream, default, cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Tiff format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    public static void SaveAsTiff(this Image source, Stream stream, TiffEncoder encoder)
        => source.Save(
              stream,
              encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(TiffFormat.Instance));

    /// <summary>
    /// Saves the image to the given stream with the Tiff format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsTiffAsync(this Image source, Stream stream, TiffEncoder encoder, CancellationToken cancellationToken = default)
        => source.SaveAsync(
              stream,
              encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(TiffFormat.Instance),
              cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Webp format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    public static void SaveAsWebp(this Image source, string path) => SaveAsWebp(source, path, default);

    /// <summary>
    /// Saves the image to the given stream with the Webp format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsWebpAsync(this Image source, string path) => SaveAsWebpAsync(source, path, default);

    /// <summary>
    /// Saves the image to the given stream with the Webp format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsWebpAsync(this Image source, string path, CancellationToken cancellationToken)
        => SaveAsWebpAsync(source, path, default, cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Webp format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    public static void SaveAsWebp(this Image source, string path, WebpEncoder encoder) =>
        source.Save(
            path,
            encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(WebpFormat.Instance));

    /// <summary>
    /// Saves the image to the given stream with the Webp format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="path">The file path to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the path is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsWebpAsync(this Image source, string path, WebpEncoder encoder, CancellationToken cancellationToken = default)
        => source.SaveAsync(
              path,
              encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(WebpFormat.Instance),
              cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Webp format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    public static void SaveAsWebp(this Image source, Stream stream)
        => SaveAsWebp(source, stream, default);

    /// <summary>
    /// Saves the image to the given stream with the Webp format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsWebpAsync(this Image source, Stream stream, CancellationToken cancellationToken = default)
        => SaveAsWebpAsync(source, stream, default, cancellationToken);

    /// <summary>
    /// Saves the image to the given stream with the Webp format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    public static void SaveAsWebp(this Image source, Stream stream, WebpEncoder encoder)
        => source.Save(
              stream,
              encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(WebpFormat.Instance));

    /// <summary>
    /// Saves the image to the given stream with the Webp format.
    /// </summary>
    /// <param name="source">The image this method extends.</param>
    /// <param name="stream">The stream to save the image to.</param>
    /// <param name="encoder">The encoder to save the image with.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if the stream is null.</exception>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public static Task SaveAsWebpAsync(this Image source, Stream stream, WebpEncoder encoder, CancellationToken cancellationToken = default)
        => source.SaveAsync(
              stream,
              encoder ?? source.Configuration.ImageFormatsManager.GetEncoder(WebpFormat.Instance),
              cancellationToken);

}
