// Copyright (c) Six Labors.
// Licensed under the Six Labors Split License.

namespace SixLabors.ImageSharp.PixelFormats.PixelBlenders;

/// <summary>
/// Provides pixel blenders for formats that store associated alpha.
/// </summary>
internal static partial class AssociatedAlphaPixelBlenders<TPixel>
    where TPixel : unmanaged, IPixel<TPixel>
{
    /// <summary>
    /// Gets the blender for the requested color blending and alpha composition modes.
    /// </summary>
    /// <param name="colorMode">The color blending mode.</param>
    /// <param name="alphaMode">The alpha composition mode.</param>
    /// <returns>The pixel blender.</returns>
    public static PixelBlender<TPixel> GetPixelBlender(PixelColorBlendingMode colorMode, PixelAlphaCompositionMode alphaMode)
    {
        return alphaMode switch
        {
            PixelAlphaCompositionMode.Src => colorMode switch
            {
                PixelColorBlendingMode.Multiply => MultiplySrc,
                PixelColorBlendingMode.Add => AddSrc,
                PixelColorBlendingMode.Subtract => SubtractSrc,
                PixelColorBlendingMode.Screen => ScreenSrc,
                PixelColorBlendingMode.Darken => DarkenSrc,
                PixelColorBlendingMode.Lighten => LightenSrc,
                PixelColorBlendingMode.Overlay => OverlaySrc,
                PixelColorBlendingMode.HardLight => HardLightSrc,
                PixelColorBlendingMode.ColorDodge => ColorDodgeSrc,
                PixelColorBlendingMode.ColorBurn => ColorBurnSrc,
                PixelColorBlendingMode.SoftLight => SoftLightSrc,
                PixelColorBlendingMode.Difference => DifferenceSrc,
                PixelColorBlendingMode.Exclusion => ExclusionSrc,
                PixelColorBlendingMode.Hue => HueSrc,
                PixelColorBlendingMode.Saturation => SaturationSrc,
                PixelColorBlendingMode.Color => ColorSrc,
                PixelColorBlendingMode.Luminosity => LuminositySrc,
                _ => NormalSrc,
            },
            PixelAlphaCompositionMode.SrcAtop => colorMode switch
            {
                PixelColorBlendingMode.Multiply => MultiplySrcAtop,
                PixelColorBlendingMode.Add => AddSrcAtop,
                PixelColorBlendingMode.Subtract => SubtractSrcAtop,
                PixelColorBlendingMode.Screen => ScreenSrcAtop,
                PixelColorBlendingMode.Darken => DarkenSrcAtop,
                PixelColorBlendingMode.Lighten => LightenSrcAtop,
                PixelColorBlendingMode.Overlay => OverlaySrcAtop,
                PixelColorBlendingMode.HardLight => HardLightSrcAtop,
                PixelColorBlendingMode.ColorDodge => ColorDodgeSrcAtop,
                PixelColorBlendingMode.ColorBurn => ColorBurnSrcAtop,
                PixelColorBlendingMode.SoftLight => SoftLightSrcAtop,
                PixelColorBlendingMode.Difference => DifferenceSrcAtop,
                PixelColorBlendingMode.Exclusion => ExclusionSrcAtop,
                PixelColorBlendingMode.Hue => HueSrcAtop,
                PixelColorBlendingMode.Saturation => SaturationSrcAtop,
                PixelColorBlendingMode.Color => ColorSrcAtop,
                PixelColorBlendingMode.Luminosity => LuminositySrcAtop,
                _ => NormalSrcAtop,
            },
            PixelAlphaCompositionMode.SrcIn => colorMode switch
            {
                PixelColorBlendingMode.Multiply => MultiplySrcIn,
                PixelColorBlendingMode.Add => AddSrcIn,
                PixelColorBlendingMode.Subtract => SubtractSrcIn,
                PixelColorBlendingMode.Screen => ScreenSrcIn,
                PixelColorBlendingMode.Darken => DarkenSrcIn,
                PixelColorBlendingMode.Lighten => LightenSrcIn,
                PixelColorBlendingMode.Overlay => OverlaySrcIn,
                PixelColorBlendingMode.HardLight => HardLightSrcIn,
                PixelColorBlendingMode.ColorDodge => ColorDodgeSrcIn,
                PixelColorBlendingMode.ColorBurn => ColorBurnSrcIn,
                PixelColorBlendingMode.SoftLight => SoftLightSrcIn,
                PixelColorBlendingMode.Difference => DifferenceSrcIn,
                PixelColorBlendingMode.Exclusion => ExclusionSrcIn,
                PixelColorBlendingMode.Hue => HueSrcIn,
                PixelColorBlendingMode.Saturation => SaturationSrcIn,
                PixelColorBlendingMode.Color => ColorSrcIn,
                PixelColorBlendingMode.Luminosity => LuminositySrcIn,
                _ => NormalSrcIn,
            },
            PixelAlphaCompositionMode.SrcOut => colorMode switch
            {
                PixelColorBlendingMode.Multiply => MultiplySrcOut,
                PixelColorBlendingMode.Add => AddSrcOut,
                PixelColorBlendingMode.Subtract => SubtractSrcOut,
                PixelColorBlendingMode.Screen => ScreenSrcOut,
                PixelColorBlendingMode.Darken => DarkenSrcOut,
                PixelColorBlendingMode.Lighten => LightenSrcOut,
                PixelColorBlendingMode.Overlay => OverlaySrcOut,
                PixelColorBlendingMode.HardLight => HardLightSrcOut,
                PixelColorBlendingMode.ColorDodge => ColorDodgeSrcOut,
                PixelColorBlendingMode.ColorBurn => ColorBurnSrcOut,
                PixelColorBlendingMode.SoftLight => SoftLightSrcOut,
                PixelColorBlendingMode.Difference => DifferenceSrcOut,
                PixelColorBlendingMode.Exclusion => ExclusionSrcOut,
                PixelColorBlendingMode.Hue => HueSrcOut,
                PixelColorBlendingMode.Saturation => SaturationSrcOut,
                PixelColorBlendingMode.Color => ColorSrcOut,
                PixelColorBlendingMode.Luminosity => LuminositySrcOut,
                _ => NormalSrcOut,
            },
            PixelAlphaCompositionMode.Dest => colorMode switch
            {
                PixelColorBlendingMode.Multiply => MultiplyDest,
                PixelColorBlendingMode.Add => AddDest,
                PixelColorBlendingMode.Subtract => SubtractDest,
                PixelColorBlendingMode.Screen => ScreenDest,
                PixelColorBlendingMode.Darken => DarkenDest,
                PixelColorBlendingMode.Lighten => LightenDest,
                PixelColorBlendingMode.Overlay => OverlayDest,
                PixelColorBlendingMode.HardLight => HardLightDest,
                PixelColorBlendingMode.ColorDodge => ColorDodgeDest,
                PixelColorBlendingMode.ColorBurn => ColorBurnDest,
                PixelColorBlendingMode.SoftLight => SoftLightDest,
                PixelColorBlendingMode.Difference => DifferenceDest,
                PixelColorBlendingMode.Exclusion => ExclusionDest,
                PixelColorBlendingMode.Hue => HueDest,
                PixelColorBlendingMode.Saturation => SaturationDest,
                PixelColorBlendingMode.Color => ColorDest,
                PixelColorBlendingMode.Luminosity => LuminosityDest,
                _ => NormalDest,
            },
            PixelAlphaCompositionMode.DestAtop => colorMode switch
            {
                PixelColorBlendingMode.Multiply => MultiplyDestAtop,
                PixelColorBlendingMode.Add => AddDestAtop,
                PixelColorBlendingMode.Subtract => SubtractDestAtop,
                PixelColorBlendingMode.Screen => ScreenDestAtop,
                PixelColorBlendingMode.Darken => DarkenDestAtop,
                PixelColorBlendingMode.Lighten => LightenDestAtop,
                PixelColorBlendingMode.Overlay => OverlayDestAtop,
                PixelColorBlendingMode.HardLight => HardLightDestAtop,
                PixelColorBlendingMode.ColorDodge => ColorDodgeDestAtop,
                PixelColorBlendingMode.ColorBurn => ColorBurnDestAtop,
                PixelColorBlendingMode.SoftLight => SoftLightDestAtop,
                PixelColorBlendingMode.Difference => DifferenceDestAtop,
                PixelColorBlendingMode.Exclusion => ExclusionDestAtop,
                PixelColorBlendingMode.Hue => HueDestAtop,
                PixelColorBlendingMode.Saturation => SaturationDestAtop,
                PixelColorBlendingMode.Color => ColorDestAtop,
                PixelColorBlendingMode.Luminosity => LuminosityDestAtop,
                _ => NormalDestAtop,
            },
            PixelAlphaCompositionMode.DestOver => colorMode switch
            {
                PixelColorBlendingMode.Multiply => MultiplyDestOver,
                PixelColorBlendingMode.Add => AddDestOver,
                PixelColorBlendingMode.Subtract => SubtractDestOver,
                PixelColorBlendingMode.Screen => ScreenDestOver,
                PixelColorBlendingMode.Darken => DarkenDestOver,
                PixelColorBlendingMode.Lighten => LightenDestOver,
                PixelColorBlendingMode.Overlay => OverlayDestOver,
                PixelColorBlendingMode.HardLight => HardLightDestOver,
                PixelColorBlendingMode.ColorDodge => ColorDodgeDestOver,
                PixelColorBlendingMode.ColorBurn => ColorBurnDestOver,
                PixelColorBlendingMode.SoftLight => SoftLightDestOver,
                PixelColorBlendingMode.Difference => DifferenceDestOver,
                PixelColorBlendingMode.Exclusion => ExclusionDestOver,
                PixelColorBlendingMode.Hue => HueDestOver,
                PixelColorBlendingMode.Saturation => SaturationDestOver,
                PixelColorBlendingMode.Color => ColorDestOver,
                PixelColorBlendingMode.Luminosity => LuminosityDestOver,
                _ => NormalDestOver,
            },
            PixelAlphaCompositionMode.DestIn => colorMode switch
            {
                PixelColorBlendingMode.Multiply => MultiplyDestIn,
                PixelColorBlendingMode.Add => AddDestIn,
                PixelColorBlendingMode.Subtract => SubtractDestIn,
                PixelColorBlendingMode.Screen => ScreenDestIn,
                PixelColorBlendingMode.Darken => DarkenDestIn,
                PixelColorBlendingMode.Lighten => LightenDestIn,
                PixelColorBlendingMode.Overlay => OverlayDestIn,
                PixelColorBlendingMode.HardLight => HardLightDestIn,
                PixelColorBlendingMode.ColorDodge => ColorDodgeDestIn,
                PixelColorBlendingMode.ColorBurn => ColorBurnDestIn,
                PixelColorBlendingMode.SoftLight => SoftLightDestIn,
                PixelColorBlendingMode.Difference => DifferenceDestIn,
                PixelColorBlendingMode.Exclusion => ExclusionDestIn,
                PixelColorBlendingMode.Hue => HueDestIn,
                PixelColorBlendingMode.Saturation => SaturationDestIn,
                PixelColorBlendingMode.Color => ColorDestIn,
                PixelColorBlendingMode.Luminosity => LuminosityDestIn,
                _ => NormalDestIn,
            },
            PixelAlphaCompositionMode.DestOut => colorMode switch
            {
                PixelColorBlendingMode.Multiply => MultiplyDestOut,
                PixelColorBlendingMode.Add => AddDestOut,
                PixelColorBlendingMode.Subtract => SubtractDestOut,
                PixelColorBlendingMode.Screen => ScreenDestOut,
                PixelColorBlendingMode.Darken => DarkenDestOut,
                PixelColorBlendingMode.Lighten => LightenDestOut,
                PixelColorBlendingMode.Overlay => OverlayDestOut,
                PixelColorBlendingMode.HardLight => HardLightDestOut,
                PixelColorBlendingMode.ColorDodge => ColorDodgeDestOut,
                PixelColorBlendingMode.ColorBurn => ColorBurnDestOut,
                PixelColorBlendingMode.SoftLight => SoftLightDestOut,
                PixelColorBlendingMode.Difference => DifferenceDestOut,
                PixelColorBlendingMode.Exclusion => ExclusionDestOut,
                PixelColorBlendingMode.Hue => HueDestOut,
                PixelColorBlendingMode.Saturation => SaturationDestOut,
                PixelColorBlendingMode.Color => ColorDestOut,
                PixelColorBlendingMode.Luminosity => LuminosityDestOut,
                _ => NormalDestOut,
            },
            PixelAlphaCompositionMode.Clear => colorMode switch
            {
                PixelColorBlendingMode.Multiply => MultiplyClear,
                PixelColorBlendingMode.Add => AddClear,
                PixelColorBlendingMode.Subtract => SubtractClear,
                PixelColorBlendingMode.Screen => ScreenClear,
                PixelColorBlendingMode.Darken => DarkenClear,
                PixelColorBlendingMode.Lighten => LightenClear,
                PixelColorBlendingMode.Overlay => OverlayClear,
                PixelColorBlendingMode.HardLight => HardLightClear,
                PixelColorBlendingMode.ColorDodge => ColorDodgeClear,
                PixelColorBlendingMode.ColorBurn => ColorBurnClear,
                PixelColorBlendingMode.SoftLight => SoftLightClear,
                PixelColorBlendingMode.Difference => DifferenceClear,
                PixelColorBlendingMode.Exclusion => ExclusionClear,
                PixelColorBlendingMode.Hue => HueClear,
                PixelColorBlendingMode.Saturation => SaturationClear,
                PixelColorBlendingMode.Color => ColorClear,
                PixelColorBlendingMode.Luminosity => LuminosityClear,
                _ => NormalClear,
            },
            PixelAlphaCompositionMode.Xor => colorMode switch
            {
                PixelColorBlendingMode.Multiply => MultiplyXor,
                PixelColorBlendingMode.Add => AddXor,
                PixelColorBlendingMode.Subtract => SubtractXor,
                PixelColorBlendingMode.Screen => ScreenXor,
                PixelColorBlendingMode.Darken => DarkenXor,
                PixelColorBlendingMode.Lighten => LightenXor,
                PixelColorBlendingMode.Overlay => OverlayXor,
                PixelColorBlendingMode.HardLight => HardLightXor,
                PixelColorBlendingMode.ColorDodge => ColorDodgeXor,
                PixelColorBlendingMode.ColorBurn => ColorBurnXor,
                PixelColorBlendingMode.SoftLight => SoftLightXor,
                PixelColorBlendingMode.Difference => DifferenceXor,
                PixelColorBlendingMode.Exclusion => ExclusionXor,
                PixelColorBlendingMode.Hue => HueXor,
                PixelColorBlendingMode.Saturation => SaturationXor,
                PixelColorBlendingMode.Color => ColorXor,
                PixelColorBlendingMode.Luminosity => LuminosityXor,
                _ => NormalXor,
            },
            PixelAlphaCompositionMode.Plus => colorMode switch
            {
                PixelColorBlendingMode.Multiply => MultiplyPlus,
                PixelColorBlendingMode.Add => AddPlus,
                PixelColorBlendingMode.Subtract => SubtractPlus,
                PixelColorBlendingMode.Screen => ScreenPlus,
                PixelColorBlendingMode.Darken => DarkenPlus,
                PixelColorBlendingMode.Lighten => LightenPlus,
                PixelColorBlendingMode.Overlay => OverlayPlus,
                PixelColorBlendingMode.HardLight => HardLightPlus,
                PixelColorBlendingMode.ColorDodge => ColorDodgePlus,
                PixelColorBlendingMode.ColorBurn => ColorBurnPlus,
                PixelColorBlendingMode.SoftLight => SoftLightPlus,
                PixelColorBlendingMode.Difference => DifferencePlus,
                PixelColorBlendingMode.Exclusion => ExclusionPlus,
                PixelColorBlendingMode.Hue => HuePlus,
                PixelColorBlendingMode.Saturation => SaturationPlus,
                PixelColorBlendingMode.Color => ColorPlus,
                PixelColorBlendingMode.Luminosity => LuminosityPlus,
                _ => NormalPlus,
            },
            _ => colorMode switch
            {
                PixelColorBlendingMode.Multiply => MultiplySrcOver,
                PixelColorBlendingMode.Add => AddSrcOver,
                PixelColorBlendingMode.Subtract => SubtractSrcOver,
                PixelColorBlendingMode.Screen => ScreenSrcOver,
                PixelColorBlendingMode.Darken => DarkenSrcOver,
                PixelColorBlendingMode.Lighten => LightenSrcOver,
                PixelColorBlendingMode.Overlay => OverlaySrcOver,
                PixelColorBlendingMode.HardLight => HardLightSrcOver,
                PixelColorBlendingMode.ColorDodge => ColorDodgeSrcOver,
                PixelColorBlendingMode.ColorBurn => ColorBurnSrcOver,
                PixelColorBlendingMode.SoftLight => SoftLightSrcOver,
                PixelColorBlendingMode.Difference => DifferenceSrcOver,
                PixelColorBlendingMode.Exclusion => ExclusionSrcOver,
                PixelColorBlendingMode.Hue => HueSrcOver,
                PixelColorBlendingMode.Saturation => SaturationSrcOver,
                PixelColorBlendingMode.Color => ColorSrcOver,
                PixelColorBlendingMode.Luminosity => LuminositySrcOver,
                _ => NormalSrcOver,
            },
        };
    }
}
